# Generated by Django 2.1 on 2020-05-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaintlinePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loop', models.CharField(max_length=10, null=True)),
                ('startSkid', models.CharField(max_length=10, null=True)),
                ('endSkid', models.CharField(max_length=10, null=True)),
                ('skidQty', models.CharField(max_length=10, null=True)),
                ('quantity', models.CharField(max_length=10, null=True)),
                ('actualQty', models.CharField(max_length=10, null=True)),
                ('bypassQty', models.CharField(max_length=10, null=True)),
                ('mo', models.CharField(max_length=30, null=True)),
                ('itemNo', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('color', models.CharField(max_length=100, null=True)),
                ('prodType', models.CharField(max_length=20, null=True)),
                ('seqId', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkidEfficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('rate', models.CharField(max_length=10)),
            ],
        ),
    ]
