# Generated by Django 3.0 on 2021-04-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_intepreter_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=255)),
                ('password', models.CharField(default='', max_length=255)),
                ('userFirstName', models.CharField(max_length=100)),
                ('userLastName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('registerDate', models.DateField(null=True)),
            ],
        ),
    ]
