# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'initUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets

from printLabel import Ui_PrinterWindow
from printLibs  import libs

class Ui_MainWindow(object):

    def openWindow(self, label):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_PrinterWindow()
        self.ui.setupUi(self.window, label)
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1044, 630)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)

        self.MHMX_ASAY_4CYL = QtWidgets.QPushButton(self.centralwidget)
        self.MHMX_ASAY_4CYL.setGeometry(QtCore.QRect(570, 430, 180, 30))
        self.MHMX_ASAY_4CYL.setFont(font)
        self.MHMX_ASAY_4CYL.setObjectName("MHMX_ASAY_4CYL")
        self.MHMX_ASAY_4CYL.clicked.connect(lambda: self.openWindow("MHMX_ASAY_4CYL"))
        
        self.MHMX_ASAY_6CYL = QtWidgets.QPushButton(self.centralwidget)
        self.MHMX_ASAY_6CYL.setGeometry(QtCore.QRect(570, 470, 180, 30))
        self.MHMX_ASAY_6CYL.setFont(font)
        self.MHMX_ASAY_6CYL.setObjectName("MHMX_ASAY_6CYL")
        self.MHMX_ASAY_6CYL.clicked.connect(lambda: self.openWindow("MHMX_ASAY_6CYL"))
        
        self.MHMX_FRONT_LICENSE = QtWidgets.QPushButton(self.centralwidget)
        self.MHMX_FRONT_LICENSE.setGeometry(QtCore.QRect(570, 260, 180, 30))
        self.MHMX_FRONT_LICENSE.setFont(font)
        self.MHMX_FRONT_LICENSE.setObjectName("MHMX_FRONT_LICENSE")
        self.MHMX_FRONT_LICENSE.clicked.connect(lambda: self.openWindow("MHMX_FRONT_LICENSE"))
        
        self.MHMX_PI_AMARILLA = QtWidgets.QPushButton(self.centralwidget)
        self.MHMX_PI_AMARILLA.setGeometry(QtCore.QRect(10, 500, 180, 30))
        self.MHMX_PI_AMARILLA.setFont(font)
        self.MHMX_PI_AMARILLA.setObjectName("MHMX_PI_AMARILLA")
        self.MHMX_PI_AMARILLA.clicked.connect(lambda: self.openWindow("MHMX_PI_AMARILLA"))
        
        self.MHMX_PI_SERIAL = QtWidgets.QPushButton(self.centralwidget)
        self.MHMX_PI_SERIAL.setGeometry(QtCore.QRect(10, 330, 180, 30))
        self.MHMX_PI_SERIAL.setFont(font)
        self.MHMX_PI_SERIAL.setObjectName("MHMX_PI_SERIAL")
        self.MHMX_PI_SERIAL.clicked.connect(lambda: self.openWindow("MHMX_PI_SERIAL"))
        
        self.MHMX_STOSS_ABSORBER = QtWidgets.QPushButton(self.centralwidget)
        self.MHMX_STOSS_ABSORBER.setGeometry(QtCore.QRect(570, 110, 180, 30))
        self.MHMX_STOSS_ABSORBER.setFont(font)
        self.MHMX_STOSS_ABSORBER.setObjectName("MHMX_STOSS_ABSORBER")
        self.MHMX_STOSS_ABSORBER.clicked.connect(lambda: self.openWindow("MHMX_STOSS_ABSORBER"))
        
        self.MHMX_PRODUCTION = QtWidgets.QPushButton(self.centralwidget)
        self.MHMX_PRODUCTION.setGeometry(QtCore.QRect(10, 110, 180, 30))
        self.MHMX_PRODUCTION.setFont(font)
        self.MHMX_PRODUCTION.setObjectName("MHMX_PRODUCTION")
        self.MHMX_PRODUCTION.clicked.connect(lambda: self.openWindow("MHMX_PRODUCTION"))

        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(800, 380, 171, 171))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(260, 260, 241, 171))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(200, 10, 361, 231))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(760, 230, 271, 101))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_7.setGeometry(QtCore.QRect(760, 60, 271, 111))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_8.setGeometry(QtCore.QRect(260, 450, 241, 141))
        self.textBrowser_8.setObjectName("textBrowser_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1044, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "IMM Printer"))
        self.MHMX_ASAY_4CYL.setText(_translate("MainWindow", "MHMX_ASAY_4CYL"))
        self.MHMX_ASAY_6CYL.setText(_translate("MainWindow", "MHMX_ASAY_6CYL"))
        self.MHMX_FRONT_LICENSE.setText(_translate("MainWindow", "MHMX_FRONT_LICENSE"))
        self.MHMX_PI_AMARILLA.setText(_translate("MainWindow", "MHMX_PI_AMARILLA"))
        self.MHMX_PI_SERIAL.setText(_translate("MainWindow", "MHMX_PI_SERIAL"))
        self.MHMX_STOSS_ABSORBER.setText(_translate("MainWindow", "MHMX_STOSS_ABSORBER"))
        self.MHMX_PRODUCTION.setText(_translate("MainWindow", "MHMX_PRODUCTION"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/label/MHMX_ASAY_6CYL.jpg\" /></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/label/MHMX_PI_Serial.jpg\" /></p></body></html>"))
        self.textBrowser_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/label/MHMX_Production.jpg\" /></p></body></html>"))
        self.textBrowser_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/label/MHMX_FRONT_LICENSE.jpg\" /></p></body></html>"))
        self.textBrowser_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/label/MHMX_STOSS_ABSORBER.jpg\" /></p></body></html>"))
        self.textBrowser_8.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/label/MHMX_PI_Amarilla.jpg\" /></p></body></html>"))
import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
