# Generated by Django 3.0.2 on 2020-01-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='add_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
