# Generated by Django 3.0 on 2021-03-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineTest', '0002_auto_20210316_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
