# Generated by Django 3.0 on 2021-04-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineTest', '0003_users_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('FundID', models.IntegerField()),
                ('FundName', models.CharField(default='', max_length=255)),
                ('avgIncrease', models.DecimalField(decimal_places=28, max_digits=30)),
                ('increaseRate', models.DecimalField(decimal_places=28, max_digits=30)),
            ],
        ),
    ]
